bookproject/accounts/urls.py
from . import views
from django.urls import path

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
]

bookproject/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path("", views.book_list, name="book_list"),
    path("detail/<int:pk>/", views.book_detail, name="book_detail"),
    path("create/", views.book_create, name="book_create"),
    path("update/<int:pk>/", views.book_update, name="book_update"),
    path("delete/<int:pk>/", views.book_delete, name="book_delete"),
    path("review/<int:pk>/", views.book_review, name="book_review"),
]

bookproject/bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("book/", include("book.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookproject/accounts/models.py
from django.db import models

# Create your models here.

bookproject/book/models.py
from django.db import models
from django.contrib.auth.models import User
from .consts import MAX_RATE

RATE_CHOICES = [(x, str(x)) for x in range(0, MAX_RATE + 1)]


class Book(models.Model):
    CATEGORY_CHOICES = (
        ("business", "ビジネス"),
        ("lifestyle", "生活"),
        ("other", "その他"),
    )

    title = models.CharField(max_length=100, verbose_name="タイトル")
    thumbnail = models.ImageField(
        upload_to="book/picture", blank=True, null=True, verbose_name="サムネイル"
    )
    text = models.TextField(verbose_name="内容")
    category = models.CharField(
        max_length=20, choices=CATEGORY_CHOICES, verbose_name="カテゴリー"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="ユーザー", related_name="books"
    )

    def __str__(self):
        return self.title


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="書籍")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="ユーザー")
    title = models.CharField(max_length=100, verbose_name="レビュータイトル")
    text = models.TextField(verbose_name="レビュー内容")
    rate = models.IntegerField(choices=RATE_CHOICES, verbose_name="評価")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")

    def __str__(self):
        return f"{self.title} - {self.user.username} - {self.book.title}"

bookproject/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

bookproject/book/forms.py
from django.forms import ModelForm
from .models import Book
from .models import Review


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ["title", "text", "category", "thumbnail", "user"]
        labels = {
            "title": "タイトル",
            "text": "内容",
            "category": "カテゴリー",
            "thumbnail": "サムネイル",
            "user": "ユーザー",
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["title", "text", "rate"]
        labels = {
            "title": "レビュータイトル",
            "text": "本文",
            "rate": "星の数",
        }

bookproject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from .forms import SignUpForm
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class UserLoginView(LoginView):
    template_name = "registration/login.html"


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect("book:book_list")


class UserSignUpView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, "registration/signup.html", {"form": form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")
        return render(request, "registration/signup.html", {"form": form})


login_view = UserLoginView.as_view()
logout_view = UserLogoutView.as_view()
signup_view = UserSignUpView.as_view()

bookproject/book/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book, Review
from django.views.generic import ListView
from .forms import BookForm, ReviewForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Avg
from django.core.paginator import Paginator
from .consts import ITEM_PER_PAGE


class ListBookView(ListView):
    def get(self, request):
        books = Book.objects.all().order_by("-id")

        paginator = Paginator(books, ITEM_PER_PAGE)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        ranking_list = Book.objects.annotate(average_rate=Avg("review__rate")).order_by(
            "-average_rate"
        )[:5]

        return render(
            request,
            "book/list.html",
            {"books": page_obj, "ranking_list": ranking_list, "page_obj": page_obj},
        )


class DetailBookView(ListView):
    def get(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        reviews = Review.objects.filter(book=book)
        return render(request, "book/detail.html", {"book": book, "reviews": reviews})


class CreateBookView(LoginRequiredMixin, ListView):
    def get(self, request):
        form = BookForm()
        return render(request, "book/create.html", {"form": form})

    def post(self, request):
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("book:book_list")
        return render(request, "book/create.html", {"form": form})


class UpdateBookView(LoginRequiredMixin, ListView):
    def get(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        form = BookForm(instance=book)
        return render(request, "book/update.html", {"form": form, "book": book})

    def post(self, request, pk):
        book = get_object_or_404(Book, pk=pk)

        if request.user != book.user:
            raise PermissionDenied("You do not have permission to edit this book.")

        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect("book:book_list")
        return render(request, "book/update.html", {"form": form})


class DeleteBookView(LoginRequiredMixin, ListView):
    def get(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        return render(request, "book/delete_confirm.html", {"book": book})

    def post(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        if request.user != book.user:
            raise PermissionDenied("You do not have permission to edit this book.")
        book.delete()
        return redirect("book:book_list")


class ReviewBookView(LoginRequiredMixin, ListView):
    def get(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        form = ReviewForm()
        return render(request, "book/review.html", {"form": form, "book": book})

    def post(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.book = book
            review.user = request.user
            review.save()
            return redirect("book:book_detail", pk=pk)
        return render(request, "book/review.html", {"form": form, "book": book})


book_list = ListBookView.as_view()
book_detail = DetailBookView.as_view()
book_create = CreateBookView.as_view()
book_update = UpdateBookView.as_view()
book_delete = DeleteBookView.as_view()
book_review = ReviewBookView.as_view()

bookproject/templates/book/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新規作成画面</title>
</head>
<body>
    <h1>新規作成画面</h1>
    <form method="POST" action="{% url 'book:book_create' %}"  enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">作成</button>
    </form>
    <a href="{% url 'book:book_list' %}">戻る</a>
    <a href="{% url 'book:book_list' %}">一覧へ</a>
    
</body>
</html>

bookproject/templates/book/delete_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>書籍削除確認画面</title>
</head>
<body>
    <h1>書籍削除確認画面</h1>
    <p>{{ book.title }}を本当に削除しますか？</p>
    
    <form method="POST" action="{% url 'book:book_delete' book.id %}">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
    <a href="{% url 'book:book_list' %}">戻る</a>

    
</body>
</html>

bookproject/templates/book/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>books 詳細画面</title>
</head>
<body>
    <h1>books 詳細画面</h1>
    <h2>{{ book.title }}</h2>
    <p>{{ book.text }}</p>
    <p>{{ book.category }}</p>

    <h2>{{ book.title }} のレビュー一覧</h2>
    
    {% if reviews %}
    <ul>
        {% for review in reviews %}
        <li>
            <strong>{{ review.title }}</strong>（評価：{{ review.rate }}）<br>
            {{ review.text }}<br>
            by {{ review.user.username }}
        </li>     
        {% endfor %}
    </ul>
    
    {% else %}
    <p>レビューはまだありません。</p>
    
    {% endif %}


    <a href="{% url 'book:book_review' book.id %}">レビュー作成</a>
    <a href="{% url 'book:book_list' %}">戻る</a>

    <a href="{% url 'book:book_update' book.id %}">編集</a>
    <a href="{% url 'book:book_delete' book.id %}">削除</a>


</body>
</html>

bookproject/templates/book/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booksリスト画面</title>
</head>
<body>
    <h1>Booksリスト画面</h1>

    {% if request.user.is_authenticated %}
        <p>ようこそ、{{ request.user.username }}さん</p>
        <a href="{% url 'accounts:logout' %}">ログアウト</a>

    {% else %}
        <a href="{% url 'accounts:login' %}">ログイン</a>
        <a href="{% url 'accounts:signup' %}">新規登録</a>
    {% endif %}    
    <ul>
        {% for book in books %}
        <li>
            <a href="{% url 'book:book_detail' book.id %}">{{ book.title }}</a>
            {% if book.thumbnail %}
              <img src="{{ book.thumbnail.url }}" alt="{{ book.title }}"><br>
              
            {% else %}
              <p>画像は未登録です。</p>
              
            {% endif %}
            <p>{{ book.text }}</p>
            <p>{{ book.category }}</p>
        </li>
        {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">最初</a>
            <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
          {% endif %}
      
          <span class="current">
            {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}ページ
          </span>
      
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">次へ</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">最後</a>
          {% endif %}
        </span>
      </div>

    <h2>ランキング順</h2>
    {% for ranking_book in ranking_list %}
        <li>
            <a href="{% url 'book:book_detail' ranking_book.id %}">{{ ranking_book.title }}</a>

            {% if not ranking_book.average_rate %}
              <p>評価点数: まだ評価されていません</p>
            {% else %}
              <p>評価点数: {{ ranking_book.average_rate|floatformat:2 }}</p>
            {% endif %}

            {% if ranking_book.thumbnail %}
              <img src="{{ ranking_book.thumbnail.url }}" alt="{{ ranking_book.title }}"><br>
              
            {% else %}
              <p>画像は未登録です。</p>
              
            {% endif %}
            <p>{{ ranking_book.text }}</p>
            <p>{{ ranking_book.category }}</p>
        </li>
    {% endfor %}

    <a href="{% url 'book:book_create' %}">新規作成</a>

    
</body>
</html>

bookproject/templates/book/review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>レビュー作成画面</title>
</head>
<body>
    <h1>レビュー作成画面</h1>
    <form method="post">
        {% csrf_token %}
        <label>対象書籍:</label>
        <input type="text" value="{{ book.title }}" readonly><br>

        <label>タイトル:</label>
        <input type="text" name="title" required><br>

        <label>本文:</label>
        <textarea name="text" required></textarea><br>

        <label>星の数:</label>
        <select name="rate" required>
            <option value="0">1(最低)</option>
            <option value="1">2</option>
            <option value="2">3</option>
            <option value="3">4</option>
            <option value="4">5(最高)</option>
        </select>
        <br>
        {% if form.errors %}
          <span>入力内容をご確認してください</span>
          <br>
        {% endif %}
        <button type="submit">レビューを作成</button>

        
    </form>
</body>
</html>

bookproject/templates/book/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>書籍更新画面</title>
</head>
<body>
    <h1>書籍更新画面</h1>
    <form method="POST" action="{% url 'book:book_update' book.id %}"  enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">更新</button>
    </form>
    <a href="{% url 'book:book_list' %}">戻る</a>
</body>
</html>